#!/bin/bash
# Does the committed HavenApp.xcodeproj still contain everything project.yml
# would generate — and vice versa?
#
# Why this exists: `xcodegen generate` rewrites the project from project.yml
# alone, so any file the yml does not name is silently dropped from the target.
# It cost us notification.mp3 twice in one day, and both times the build was
# green: a missing resource is a runtime absence, not a compile error.
#
# Run it before merging a branch that regenerated the project. Two projects
# generated by different runs have entirely different UUIDs, so a merge is a
# choice of one lineage over the other rather than a union — this tells you
# what that choice would cost.
#
# Usage: scripts/check-project-sync.sh [--quiet]
# Exit:  0 the two agree (modulo the cosmetic allowlist), 1 they do not.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/HavenApp"
COMMITTED="$APP_DIR/HavenApp.xcodeproj/project.pbxproj"

# Differences that are noise rather than a missing file. `path =` spelling can
# differ between a SOURCE_ROOT reference and the generated relative form, so
# compare basenames, and ignore the editor workspace the generator picks up.
ALLOWLIST_REGEX='^BUD-14\.code-workspace$'

command -v xcodegen >/dev/null || { echo "xcodegen not installed"; exit 1; }
[ -f "$COMMITTED" ] || { echo "no committed project at $COMMITTED"; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Generate into a throwaway copy so the working tree is never touched — running
# the generator to test the generator would defeat the point.
cp -R "$APP_DIR" "$WORK/HavenApp"
(cd "$WORK/HavenApp" && xcodegen generate >/dev/null)

paths_in() {
    # Basenames of every `path = ...;` entry, deduped.
    sed -n 's/.*[^A-Za-z]path = "\{0,1\}\([^";]*\)"\{0,1\};.*/\1/p' "$1" \
        | sed 's:.*/::' | sort -u | grep -Ev "$ALLOWLIST_REGEX" || true
}

paths_in "$COMMITTED" > "$WORK/committed.txt"
paths_in "$WORK/HavenApp/HavenApp.xcodeproj/project.pbxproj" > "$WORK/generated.txt"

DROPPED="$(comm -23 "$WORK/committed.txt" "$WORK/generated.txt")"
ADDED="$(comm -13 "$WORK/committed.txt" "$WORK/generated.txt")"

status=0
if [ -n "$DROPPED" ]; then
    echo "Regenerating would DROP these from the project:"
    echo "$DROPPED" | sed 's/^/  - /'
    echo "  -> name them in HavenApp/project.yml, or they leave the build silently."
    status=1
fi
if [ -n "$ADDED" ]; then
    echo "The committed project is MISSING files project.yml would add:"
    echo "$ADDED" | sed 's/^/  + /'
    echo "  -> regenerate, or the committed project is stale."
    status=1
fi
if [ "$status" -eq 0 ] && [ "${1:-}" != "--quiet" ]; then
    echo "project.yml and the committed project agree ($(wc -l < "$WORK/committed.txt" | tr -d ' ') paths)."
fi
exit "$status"
